export const data=[
    {
        label:'FirstCard',
        color:'red',
        style:{
            height:'600px',
            width:'100%',
            backgroundColor:'greenyellow',
            textAlign:'center',
        }
    },
    {
        label:'SecondCard',
        color:'yellow',
        style:{
            height:'600px',
            width:'100%',
            backgroundColor:'orange',
            textAlign:'center',
        }
    },
    {
        label:'ThirdCard',
        color:'red',
        style:{
            height:'600px',
            width:'100%',
            backgroundColor:'red',
            textAlign:'center',
        },
    },
    {
        label:'FourthCard',
        color:'red',
        style:{
            height:'600px',
            width:'100%',
            backgroundColor:'blue',
            textAlign:'center', 
        }
    },
    {
        label:'FirstCard',
        color:'red',
        style:{
            height:'600px',
            width:'100%',
            backgroundColor:'purple',
            textAlign:'center',
        }
    }
]